#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

action="$1"

# If there's a backup of ssl.load, restore it (but first make sure that the
# path we're moving to is either a regular file or doesn't exist).
test -f /etc/apache2/mods-available/ssl.load.orig && \
  test \( -f /etc/apache2/mods-available/ssl.load -o \
         ! -e /etc/apache2/mods-available/ssl.load \) && \
  mv /etc/apache2/mods-available/ssl.load.orig \
     /etc/apache2/mods-available/ssl.load

# Only do complete clean-up on purge.
if [ "$action" != "purge" ] ; then
  exit 0
fi

@@include@@../common/apt.include

# Only remove the defaults file if it is not empty. An empty file was probably
# put there by the sysadmin to disable automatic repository configuration, as
# per the instructions on the package download page.
if [ -s "$DEFAULTS_FILE" ]; then
  # Make sure the package defaults are removed before the repository config,
  # otherwise it could result in the repository config being removed, but the
  # package defaults remain and are set to not recreate the repository config.
  # In that case, future installs won't recreate it and won't get auto-updated.
  rm "$DEFAULTS_FILE" || exit 1
fi
# Remove any Google repository added by the package.
clean_sources_lists
